apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-riker
  namespace: argocd
  labels:
    {{- toYaml .Values.app.labels | nindent 4 }}  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-riker
    server: {{ .Values.app.spec.destination.server }}
  source:
    repoURL: {{ .Values.app.spec.source.repoURL }}
    targetRevision: {{ .Values.app.spec.source.targetRevision }}
    path: teams/team-riker/dev
    helm:
      values: |
        {{- toYaml .Values.app | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true